#!/usr/bin/python

import os
import time
import argparse

parser = argparse.ArgumentParser(description='Reconstruction: \
                          hdf5 to mrc + reconstruction + trim')
parser.add_argument('aligned_hdf5', type=str, 
                    help='Enter hdf5 or mrc containing aligned stack')
parser.add_argument('-i', '--iterations', type=int, default=30, 
                    help='Iterations for tomo3d (default=30)')

args = parser.parse_args()
align_hdf5 = args.aligned_hdf5

align_tree_hdf5 = 'FastAligned/tomo_aligned@' + align_hdf5
print(align_tree_hdf5)

align_name, fileExtension = os.path.splitext(align_hdf5)
align_mrc = align_name + '.mrc'
print(align_mrc)

xmipp_image_convert = "scipion xmipp_image_convert"
os.system(xmipp_image_convert + " -i " + align_tree_hdf5 + " -o " + align_mrc)
time.sleep(2)

tilt_angles = 'angles.tlt'
align_xzy = align_name.replace("_ali","_recons") + '.xzy'

tomo3d_cmd = ("tomo3d -v 1 -l " + str(args.iterations) + " -z 500 -S -a " +  
              tilt_angles + " -i " + align_mrc + " -o " + align_xzy)
os.system(tomo3d_cmd) 

align_xyz = align_name.replace("_ali","_recons") + ".xyz"
print(align_xyz)
trimvol_cmd = ("trimvol -yz " + align_xzy + " " + align_xyz)
os.system(trimvol_cmd)





