#!/usr/bin/python

"""
(C) Copyright 2015 Marc Rosanes
The program is distributed under the terms of the 
GNU General Public License (or the Lesser GPL).

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import os
import time
import argparse

parser = argparse.ArgumentParser(description='Reconstruction: \
                          hdf5 to mrc + reconstruction + trim')
parser.add_argument('aligned_hdf5', type=str, 
                    help='Enter hdf5 or mrc containing aligned stack')
parser.add_argument('-i', '--iterations', type=int, default=30, 
                    help='Iterations for tomo3d (default=30)')

args = parser.parse_args()
start_time = time.time()

align_hdf5 = args.aligned_hdf5

align_tree_hdf5 = 'FastAligned/tomo_aligned@' + align_hdf5
print(align_tree_hdf5)

align_name, fileExtension = os.path.splitext(align_hdf5)
align_mrc = align_name + '.mrc'
print(align_mrc)

xmipp_image_convert = "scipion xmipp_image_convert"
cmd = xmipp_image_convert + " -i " + align_tree_hdf5 + " -o " + align_mrc
print(cmd)
os.system(cmd)
time.sleep(2)

tilt_angles = 'angles.tlt'
align_xzy = align_name.replace("_ali","_recons") + '.xzy'

tomo3d_cmd = ("tomo3d -v 1 -l " + str(args.iterations) + " -z 500 -S -a " +  
              tilt_angles + " -i " + align_mrc + " -o " + align_xzy)
os.system(tomo3d_cmd) 

align_xyz = align_name.replace("_ali","_recons") + ".xyz"
print(align_xyz)
trimvol_cmd = ("trimvol -yz " + align_xzy + " " + align_xyz)
os.system(trimvol_cmd)

print("\nTOTAL ELAPSED TIME:")
print("--- %s minutes ---\n" % ((time.time() - start_time)/60))





