#!/usr/bin/python

"""
(C) Copyright 2015 Marc Rosanes
The program is distributed under the terms of the 
GNU General Public License (or the Lesser GPL).

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import os
import time
import argparse

parser = argparse.ArgumentParser(description='txrm2nexus + normalize')

parser.add_argument('raw_data_txrm', type=str, 
                    help='Enter txrm containing raw data stack.')
parser.add_argument('raw_FF_txrm', type=str, 
                    help='Enter txrm containing raw FF stack.')

args = parser.parse_args()

start_time = time.time()

raw_data_txrm = args.raw_data_txrm
raw_FF_txrm = args.raw_FF_txrm
os.system("txrm2nexus " + raw_data_txrm + " " + raw_FF_txrm + " -o=sb")

rawtxrm_name, fExt = os.path.splitext(raw_data_txrm)
raw_hdf5 = rawtxrm_name + '.hdf5'
os.system('normalize ' + raw_hdf5)

rawhdf5_name, fExt = os.path.splitext(raw_hdf5)
norm_hdf5 = rawtxrm_name + '_norm.hdf5'

print("\nTOTAL ELAPSED TIME:")
print("--- %s minutes ---\n" % ((time.time() - start_time)/60))
